python3 unstable.py \
    --model_name "Qwen/Qwen3-4B" \
    --wandb \
    --num_actors 2 \
    --num_learners 1 \
    --lr 1e-5 \
    --batch_size 32 \
    --gradient_accumulation_steps 32 \
    --max_tokens 512 \
    --gradient_checkpointing \
    --bf16_training \
    --num_collection_workers 384 \
    --num_evaluation_workers 8
