python3 unstable.py \
    --model_name "Qwen/Qwen3-4B-base" \
    --train_env_id "SimpleTak-v0-train:2:qwen3-game" \
    --eval_env_id "SimpleTak-v0-train:2:qwen3-game,Dataset-AIME24-v0-all:1:qwen3-reasoning "\
    --wandb \
    --num_actors 7 \
    --num_learners 1 \
    --lr 5e-5 \
    --batch_size 384 \
    --gradient_accumulation_steps 384 \
    --max_tokens 4096 \
    --gradient_checkpointing \
    --bf16_training \
    --num_collection_workers 384 \
    --num_evaluation_workers 32 \
    --lora_rank 64 \
    --lora_alpha 64 \
    --lora_dropout 0 \
    --self_play_opponent_lag_lower 5 \
    --self_play_opponent_lag_upper 9 \
    --format_reward_think 1.5 \
    --format_reward_valid_move 1.0 \
    --format_penalty_invalid_move -1.0\
    --observation_format_template "qwen3"\
    --eval_games_per_update_step 64\
    --gradient_clip 0.05
