python3 unstable.py \
    --model_name "Qwen/Qwen3-0.6B" \
    --wandb \
    --num_actors 2 \
    --num_learners 2 \
    --lr 1e-5 \
    --batch_size 128 \
    --gradient_accumulation_steps 64 \
    --max_tokens 2048 \
    --gradient_checkpointing \
    --bf16_training \
    --num_collection_workers 384 \
    --num_evaluation_workers 8
